### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by davidpowellme** [ramseykjenna/LinkedIn-Redesign#1]
I realize you're still working on this design, but based on your mockups and what coding you have done of the Material Design version of this, I can say it's a breath of fresh air to people who find LinkedIn's current dashboard claustrophobia-inducing.

For box-shadow the exact way Google does it, you might find this cheat sheet helpful: [https://gist.github.com/gefangenimnetz/3ef3e18364edf105c5af#file-materialdesignshadowhelper-less](https://gist.github.com/gefangenimnetz/3ef3e18364edf105c5af#file-materialdesignshadowhelper-less)

**Comment by ramseykjenna** [comment]
Thanks David!
