### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by amaliebarras** [ramseykjenna/LinkedIn-Redesign#2]
<img width="463" alt="screen shot 2016-04-06 at 10 15 53 am" src="https://cloud.githubusercontent.com/assets/11826646/14321880/9b2852a8-fbe0-11e5-80d8-97553a769fcd.png">

I'm getting an error when I view yours :/ File structure maybe?

**Comment by ramseykjenna** [comment]
to fix, /google.html after localhost4000. That should fix it :)
